pragma solidity 0.4.21;

/**
* Contract that keep track of contract upgrade
*
* Auto-generated by truffle init
*/
contract Migrations {

    /** Address of contract owner */
    address public owner;
    /** Number of migration already done */
    uint public last_completed_migration;

    /** Owner-only modifier */
    modifier restricted() {
        if (msg.sender == owner) _;
    }

    /** Set owner when the contract is deployed */
    function Migrations() public {
        owner = msg.sender;
    }

    /** Set number of completed migration so truffle knows not to run them again */
    function setCompleted(uint completed) public restricted {
        last_completed_migration = completed;
    }

    /** Upgrade the Migrations contact */
    function upgrade(address new_address) public restricted {
        Migrations upgraded = Migrations(new_address);
        upgraded.setCompleted(last_completed_migration);
    }

}
